apiVersion: ray.io/v1
kind: RayService
metadata:
  name: vllm-tpu
spec:
  serveConfigV2: |
    applications:
      - name: llm
        import_path: ai-ml.gke-ray.rayserve.llm.serve_tpu:model
        deployments:
        - name: VLLMDeployment
          num_replicas: 1
        runtime_env:
          working_dir: "https://github.com/ryanaoleary/kubernetes-engine-samples/archive/refs/heads/multihost-example.zip"
          env_vars:
            MODEL_ID: "meta-llama/Meta-Llama-3-70B-Instruct"
            TPU_CHIPS: "8"
  rayClusterConfig:
    rayVersion: 2.34.0
    headGroupSpec:
      rayStartParams: {}
      template:
        spec:
          containers:
          - name: ray-head
            image: ryanaoleary/vllm:tpu
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 6379
              name: gcs
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            - containerPort: 8000
              name: serve
            env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: hf_api_token
            - name: NCCL_DEBUG
              value: TRACE
            - name: VLLM_TRACE_FUNCTION
              value: "1"
            resources:
              limits:
                cpu: "8"
                memory: 40G
              requests:
                cpu: "8"
                memory: 40G
    workerGroupSpecs:
    - groupName: tpu-group
      replicas: 1
      minReplicas: 0
      maxReplicas: 2
      numOfHosts: 2
      rayStartParams: {}
      template:
        spec:
          containers:
            - name: ray-worker
              image: ryanaoleary/vllm:tpu
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: "150"
                  google.com/tpu: "4"
                  ephemeral-storage: 150Gi
                  memory: 100G
                requests:
                  cpu: "150"
                  google.com/tpu: "4"
                  ephemeral-storage: 150Gi
                  memory: 100G
              env:
                - name: HUGGING_FACE_HUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: hf-secret
                      key: hf_api_token
                - name: NCCL_DEBUG
                  value: TRACE
                - name: VLLM_TRACE_FUNCTION
                  value: "1"
          nodeSelector:
            cloud.google.com/gke-tpu-accelerator: tpu-v4-podslice
            cloud.google.com/gke-tpu-topology: 2x2x2